name: Cross Platform Tests

on: [push, pull_request]

jobs:
  test_windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: ['windows-2019', 'windows-2022', 'windows-latest']
    steps:
    -
      name: Checkout source code
      uses: actions/checkout@v2
    -
      name: Set up Go 1.17
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.17
    - 
      name: Setup msys2 / gcc compiler
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
    - 
      name: Test (without race condition detector - not available on Windows)
      env: 
        PATH: D:\a\_temp\msys64\mingw64\bin;%PATH% #add gcc to %path%
      run: go test -v ./...

  test_ubuntu_versions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-20.04', 'ubuntu-latest']
    steps:
    -
      name: Set up Go 1.17
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.17
    -
      name: Checkout source code
      uses: actions/checkout@v1
    - 
      name: Install dependencies 
      run: sudo apt-get install -y libusb-1.0-0-dev
    -
      name: Generate & configure libusb & hidapi
      run: go generate
    -
      name: Test (with race condition detector)
      run: go test -v -race ./...

  test_go_versions:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: ['1.11', '1.12', '1.13', '1.14', '1.15', '1.16', '1.17']
    steps:
    -
      name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: ${{ matrix.go-version }}
    -
      name: Checkout source code
      uses: actions/checkout@v1
    - 
      name: Install dependencies 
      run: sudo apt-get install -y libusb-1.0-0-dev
    -
      name: Generate & configure libusb & hidapi
      run: go generate
    -
      name: Test (with race condition detector)
      run: go test -v -race ./...

  test_coverage:
    runs-on: ubuntu-20.04
    steps:
    -
      name: Set up Go 1.17
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.17
    -
      name: Checkout source code
      uses: actions/checkout@v1
    - 
      name: Install dependencies 
      run: sudo apt-get install -y libusb-1.0-0-dev
    -
      name: Generate & configure libusb & hidapi
      run: go generate
    -
      # Test on the native platform (linux/amd64)
      # Then upload the code coverage to Coveralls.io
      name: Test
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go test -race -covermode atomic -coverprofile=profile.cov ./...
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github

  test_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-10.15', 'macos-11']

    steps:
    -
      name: Set up Go 1.17
      uses: actions/setup-go@v1
      id: go
      with:
        go-version: 1.17
    -
      name: Checkout source code
      uses: actions/checkout@v1
    - 
      name: Install automake
      run: brew install automake
    -
      name: Generate & configure libusb & hidapi
      run: go generate
    -
      name: Test (with race condition detector)
      run: go test -v -race ./...